include:
  package:lint/analysis_options.yaml
  #с помощью этой строки мы подключаем все правила, которые уже до нас прописали разработчики lint

#это уже мои кастомные правила, которые появились в следствии моего опыта/потребностей, пока что список небольшой
linter:
  rules:
    - parameter_assignments

analyzer:
  errors:
    missing_required_param: error #запрещает существовать классу, если у него указаны не все обязательные параметры
    parameter_assignments: error #запрещает переопределять входные параметры ф-и
    missing_return: error #запрещает существовать ф-и у которой есть возвращаемый тип, но нет return
