name: counter_timophey
description: Special project for Hasselius.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

#Зависимости которые будует в нашем итоговом апк
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  equatable: ^1.2.5 #про это читай в [counter_event.dart]
  flutter_bloc: ^6.1.1 #старый добрый блок

#Зависимости которые не будут входить в сборку нашего итогового апк, т.е. 
#тут будут зависимости для тестов(mockito, bloc_test и т.п.) или линтер
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint:
    ^1.3.0 #это линтер, для написания адекватного, оптимального кода
    #обрати внимание на файл [analysis_options.yaml]
flutter:
  uses-material-design: true
